#!/bin/bash

#########################################################
#
# Platform: NCI Gadi HPC
#
# Author: Tracy Chew
# tracy.chew@sydney.edu.au
#
# If you use this script towards a publication, please acknowledge the
# Sydney Informatics Hub (or co-authorship, where appropriate).
#
# Suggested acknowledgement:
# The authors acknowledge the scientific and technical assistance
# <or e.g. bioinformatics assistance of <PERSON>> of Sydney Informatics
# Hub and resources and services from the National Computational
# Infrastructure (NCI), which is supported by the Australian Government
# with access facilitated by the University of Sydney.
#
#########################################################
# -l walltime=8:00:00,ncpus=48,mem=190GB,wd, only took 25 mins for 30 samples- NN
#########################################################

#PBS -P bt64
#PBS -N tpmcalculator
#PBS -l walltime=8:00:00,ncpus=48,mem=190GB,wd
#PBS -q normal
#PBS -W umask=022
#PBS -l storage=scratch/bt64
#PBS -o ./Logs/tpmcalculator.o
#PBS -e ./Logs/tpmcalculator.e

set -e

#Set the PBS_O_WORKDIR so that relative files work when queueing from the /Scripts directory
PBS_O_WORKDIR=/scratch/bt64/nn8573/eqtl/ceph/RNASeq-DE/Scripts
cd "${PBS_O_WORKDIR}"

#activate conda environment 'rnaseq-de' to access the TPMCalculator package
export PATH=$HOME/miniconda3/envs/rnaseq-de/bin:$PATH
source activate rnaseq-de

module load openmpi/4.1.0
module load nci-parallel/1.0.0a
module load bamtools/2.5.2

mkdir -p ./Logs

# NCPUS per task
NCPUS=1

SCRIPT=./tpmcalculator.sh
INPUTS=./Inputs/tpmcalculator.inputs

#########################################################
# Do not edit below this line
#########################################################

M=$(( PBS_NCI_NCPUS_PER_NODE / NCPUS )) #tasks per node

sed "s|^|${SCRIPT} |" ${INPUTS} > ${PBS_JOBFS}/input-file

mpirun --np $((M * PBS_NCPUS / PBS_NCI_NCPUS_PER_NODE)) \
        --map-by node:PE=${NCPUS} \
        nci-parallel \
        --verbose \
        --input-file ${PBS_JOBFS}/input-file

